### ISSUE TITLE
conda install -c conda-forge scipy blas=*=openblas installs the netlib version of libcblas and libblas on macOS

### ISSUE THREAD

**Issue by ogrisel** [conda-forge/scipy-feedstock#143]
Steps to reproduce **on macOS**:

```
$ conda create -y -n tmp -c conda-forge scipy blas=*=openblas
$ conda list -n tmp
# packages in environment at /Users/ogrisel/miniconda3/envs/tmp:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py39h2c36a5b_2    conda-forge
libblas                   3.9.0           1_h508aa58_netlib    conda-forge
libcblas                  3.9.0           1_h508aa58_netlib    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               5.0.0               h7cc5361_13    conda-forge
libgfortran5              9.3.0               h7cc5361_13    conda-forge
liblapack                 3.9.0           1_h508aa58_netlib    conda-forge
libopenblas               0.3.11          openmp_h54245bb_1    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
ncurses                   6.2                  hb1e8313_2    conda-forge
numpy                     1.19.2           py39h948a3a5_1    conda-forge
openblas                  0.3.11          openmp_hd4b4ca2_1    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
python                    3.9.0           ha017127_4_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
scipy                     1.5.2            py39hea380fd_2    conda-forge
setuptools                49.6.0           py39h2c36a5b_2    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
tzdata                    2020c                h516909a_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

Note that while the blas virtual package points to openblas, the libcblas and libblas packages used by scipy are actually the netlib variants. Note that libopenblas is also installed but I suspect that it is not used (for instance the output of `python -m threadpoolctl -i scipy.linalg` is empty, meaning that [threadpoolctl](https://github.com/joblib/threadpoolctl) could not detect the dynamic loading of libopenblas).

I am not sure if this is a bug in conda (as mamba is not affected, see below) or a problem with the metadata of the scipy package or the blas-related packages on conda-forge.

Additional remarks:

- the problem does not happen when using the `default` channel (there are no libcblas and libblas packages in this case);
- the is a similar problem when one does `blas=*=mkl` instead of `blas=*=openblas`;
- this does not happen if one installs numpy instead of scipy, see details:

<details>

```
$ conda create -y -n tmp -c default numpy blas=*=openblas
$ conda list -n tmp
# packages in environment at /Users/ogrisel/miniconda3/envs/tmp:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py39h2c36a5b_2    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               3.0.1                         0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10               h0794777_0
ncurses                   6.2                  hb1e8313_2    conda-forge
numpy                     1.19.2           py39h948a3a5_1    conda-forge
openblas                  0.3.3             hdc02c5d_1001    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
python                    3.9.0           ha017127_4_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
setuptools                49.6.0           py39h2c36a5b_2    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
tzdata                    2020c                h516909a_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

</details>

- mamba does not have this problem:

<details>

```
$ mamba create -y -n tmp -c conda-forge scipy blas=*=openblas
$ conda list -n tmp
# packages in environment at /Users/ogrisel/miniconda3/envs/tmp:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
ca-certificates           2020.10.14                    0
certifi                   2020.6.20        py39h2c36a5b_2    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               5.0.0               h7cc5361_13    conda-forge
libgfortran5              9.3.0               h7cc5361_13    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          openmp_h54245bb_5    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
ncurses                   6.2                  hb1e8313_2    conda-forge
numpy                     1.19.2           py39hef9df0d_1    conda-forge
openblas                  0.3.10          openmp_hd4b4ca2_5    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
python                    3.9.0           ha017127_4_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
scipy                     1.5.2            py39hea380fd_2    conda-forge
setuptools                49.6.0           py39h2c36a5b_2    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
tzdata                    2020c                h516909a_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

</details>

**Comment by ogrisel** [comment]
Also:

```
$ cat ~/.condarc
channels:
  - defaults
#channel_priority: strict
```

but that should not matter because I passed `-c conda-forge` to all the commands explicitly, right?

**Comment by h-vetinari** [comment]
I believe you're missing one extra asterisk. It should be `blas=*=*openblas`, due to the way the buildstrings are constructed. At least for `blas=*=*mkl`, this works for me.

On windows, `conda create -n test "python=3.8" scipy "blas=*=*openblas"` fails with dependency resolution errors that I cannot fully understand, but that I believe might have something to do with https://github.com/conda-forge/mkl-service-feedstock/pull/10 not having bumped the build number, leading to most [files](https://anaconda.org/conda-forge/mkl-service/files) not actually being rebuilt, which I'm fixing in https://github.com/conda-forge/mkl-service-feedstock/pull/11, cf. the following error (note the python-range for `mkl-service` does not contain 3.6-3.8):
```
Package python conflicts for:
python=3.8
scipy=1.5 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
scipy=1.5 -> mkl-service[version='>=2,<3.0a0'] -> python[version='>=2.7,<2.8.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']
```

**Comment by ogrisel** [comment]
I don't think this is the problem because I get the same results as reported above with the extra asterisk and the quotes:

```
$ conda create -y -n test -c conda-forge "python=3.8" scipy "blas=*=*openblas"
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/ogrisel/miniconda3/envs/test

  added / updated specs:
    - blas[build=*openblas]
    - python=3.8
    - scipy
...
$ conda list -n test
# packages in environment at /Users/ogrisel/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h5347e94_2    conda-forge
libblas                   3.9.0           1_h508aa58_netlib    conda-forge
libcblas                  3.9.0           1_h508aa58_netlib    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               5.0.0               h7cc5361_13    conda-forge
libgfortran5              9.3.0               h7cc5361_13    conda-forge
liblapack                 3.9.0           1_h508aa58_netlib    conda-forge
libopenblas               0.3.11          openmp_h54245bb_1    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
ncurses                   6.2                  hb1e8313_2    conda-forge
numpy                     1.19.2           py38ha98150c_1    conda-forge
openblas                  0.3.11          openmp_hd4b4ca2_1    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
python                    3.8.6           hcfdab8c_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
scipy                     1.5.2            py38h9bd2513_2    conda-forge
setuptools                49.6.0           py38h5347e94_2    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

**Comment by ogrisel** [comment]
Note: I can only observe this problem on macOS. On linux I get the openblas variants for everything as expected.

**Comment by ogrisel** [comment]
Furthermore, on macOS, not that openblas and libopenblas are actually installed and that the blas package is actually set to the openblas build. It's only the libblas / libcblas / liblapack packages that are wrong.

**Comment by ogrisel** [comment]
And also mamba installs everything correctly. So there is a problem in the way conda resolves the dependencies of that package specs on macOS.

**Comment by isuruf** [comment]
This is a problem with `current_repodata.json`. Removed https://github.com/conda-forge/admin-requests/pull/150 for now as it was causing other problems as well. Should be fixed in an hour or so

**Comment by ogrisel** [comment]
Thanks @isuruf. I will try again in an hour or so to confirm.

**Comment by ogrisel** [comment]
I have tried again and I still get the same results (netlib variant of `libblas`, `libcblas`, `liblapack`...).

**Comment by isuruf** [comment]
Can you check now?

**Comment by ogrisel** [comment]
It seems to be fixed. Thanks @isuruf.
